### ISSUE TITLE
environment_url not working

### ISSUE THREAD

**Issue by benc-uk** [chrnorm/deployment-status#10]
Really useful action! 

One thing, I notice that the task code would accept an `environment_url` parameter, when I pass it in, I see this error
```
Unexpected input 'environment_url', valid inputs are ['state', 'token', 'target-url', 'description', 'deployment_id']
```
And the environment_url is never set (as far as I can tell)

I've tried switching to the master branch and `uses: chrnorm/deployment-status@master`
and then I get an error
```
File not found: '/home/runner/work/_actions/chrnorm/deployment-status/master/lib/main.js'
```

**Comment by chrnorm** [comment]
Thanks for the issue @benc-uk! I've now merged all open PRs and fixed the release branch. The release is now live at v1.0.0 here: https://github.com/marketplace/actions/deployment-status.
