### ISSUE TITLE
old deployments are not set as `inactive`

### ISSUE THREAD

**Issue by spol-vt** [chrnorm/deployment-status#27]
When deployment is marked as a `success`, we want all `active` deployments in this environment to become `inactive`.
Currently, old deployments remain in `active` state. Trying to fetch an ID of old deployments to make them inactive via separate status update is a major pain, I think API supports `auto inactive` property that could be used here? Here is an alternative action that supports this functionality https://github.com/marketplace/actions/deployment-status-update

**Comment by chrnorm** [comment]
Thanks for the issue @spol-vt (and my apologies for the delayed response). I've fixed this in #36 and added support for `auto-inactive` - this will be included in the v2 release of this action.
