### ISSUE TITLE
Update to use node 20

### ISSUE THREAD

**Issue by bbergenroth** [chrnorm/deployment-status#48]
Node 16 is [EOL](https://nodejs.org/en/blog/announcements/nodejs16-eol/) and GH actions are [transitioning](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)

**Comment by bdlake** [comment]
@chrnorm please bump this to Node 20.

**Comment by chrnorm** [comment]
Thanks, should now be fixed: https://github.com/chrnorm/deployment-status/releases/tag/v2.0.2

**Comment by bdlake** [comment]
@chrnorm looks like `v2.0.2` doesn't have node 20 still. `main` appears to have it though: https://github.com/chrnorm/deployment-status/compare/v2.0.2...main

**Comment by chrnorm** [comment]
@bdlake thanks, should be fixed now in `v2.0.3`
